### ISSUE TITLE
app crash for Deploygate#519 when launched

### ISSUE THREAD

**Issue by yamacraft** [DroidKaigi/conference-app-2019#456]
**Overview (Required)**
- app crash when launched

**Steps To Reproduce**

1. Go to Install app for Deploygate#519
2. launch app
3. crashed for start up 

**Env:**
 - Device: Pixel3
 - OS: 9.0
 - Deploygate#519
   - Confirmed: 59633107bb9156011099875a463b99a75b8ad7bf

**Additional context**

```
2019-01-14 15:14:33.024 12309-12309/io.github.droidkaigi.confsched2019.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.confsched2019.debug, PID: 12309
    java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:79)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:54)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:373)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at io.github.droidkaigi.confsched2019.ext.android.ReceiveChannelExtKt$toLiveData$1.onActive(ReceiveChannelExt.kt:52)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214)
        at com.shopify.livedataktx.SupportMediatorLiveData.observeForever(SupportMediatorLiveData.kt:48)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214)
        at com.shopify.livedataktx.SupportMediatorLiveData.observeForever(SupportMediatorLiveData.kt:48)
        at io.github.droidkaigi.confsched2019.App.onCreate(App.kt:94)
        at io.github.droidkaigi.confsched2019.DebugApp.onCreate(DebugApp.kt:10)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.AbstractMethodError: abstract method "java.lang.String kotlinx.coroutines.internal.MainDispatcherFactory.hintOnError()"
        at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:39)
        at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:18)
        at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:10)
        at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:55)
        at io.github.droidkaigi.confsched2019.ext.android.CoroutinePlugin.<clinit>(CoroutinePlugin.kt:22)
        at io.github.droidkaigi.confsched2019.ext.android.ReceiveChannelExtKt$toLiveData$1.onActive(ReceiveChannelExt.kt:52) 
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418) 
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214) 
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141) 
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118) 
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418) 
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214) 
        at com.shopify.livedataktx.SupportMediatorLiveData.observeForever(SupportMediatorLiveData.kt:48) 
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141) 
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118) 
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418) 
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:214) 
        at com.shopify.livedataktx.SupportMediatorLiveData.observeForever(SupportMediatorLiveData.kt:48) 
        at io.github.droidkaigi.confsched2019.App.onCreate(App.kt:94) 
        at io.github.droidkaigi.confsched2019.DebugApp.onCreate(DebugApp.kt:10) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by yamacraft** [comment]
It may be the same as #455
