### ISSUE TITLE
Introduce material component for iOS App

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#495]
## Kind (Required)

- Other

 ## Overview (Required)

- I don't know about iOS, But when the error occurred , I want to use Snackbar
- Probably we should use cocoapods

**Comment by takasfz** [comment]
I need help,
build for iOS failed with following error. Does anyone know how to solve it?

```
./gradlew :frontend:ios-combined:packForXCode -PXCODE_CONFIGURATION=Debug
Parallel execution is an incubating feature.

> Configure project :model
Kotlin Multiplatform Projects are an experimental feature.

> Configure project :frontend:android
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :frontend:ios-combined:linkDebugFrameworkIOS
llvm-lto: error: Linking globals named 'ktype:io.github.droidkaigi.confsched2019.model.Announcement.Type': symbol multiply defined!
error: compilation failed: The /Users/a14042/.konan/dependencies/clang-llvm-6.0.1-darwin-macos/bin/llvm-lto command returned non-zero exit code: 1.

 * Source files: ApiEndpoint.kt, KtorDroidKaigiApi.kt, KtorGoogleFormApi.kt, AnnouncementResponseImpl.kt, CategoryItemResponseImpl.kt, CategoryResponseImpl.kt, LinkResponseImpl.kt, QuestionAnswerResponseImpl.kt, ResponseImpl.kt, RoomResponseImpl.kt, SessionMessageResponseImpl.kt, SessionResponseImpl.kt, SpeakerResponseImpl.kt, SponsorItemResponseImpl.kt, SponsorResponseImpl.kt, TranslatedNameImpl.kt, ApiComponent.kt, ApiEndpoint.kt, MainLoopDispatcher.kt, DroidKaigiApi.kt, GoogleFormApi.kt, LangParameter.kt, AnnouncementListResponse.kt, AnnouncementResponse.kt, CategoryItemResponse.kt, CategoryResponse.kt, LinkResponse.kt, QuestionAnswerResponse.kt, Response.kt, RoomResponse.kt, SessionMessageResponse.kt, SessionResponse.kt, SpeakerResponse.kt, SponsorItemResponse.kt, SponsorResponse.kt, TranslatedName.kt, AnnouncementDatabase.kt, SessionDatabase.kt, SponsorDatabase.kt, AnnouncementEntity.kt, CategoryEntity.kt, LanguageEntity.kt, MessageEntity.kt, RoomEntity.kt, SessionEntity.kt, SessionFeedback.kt, SessionSpeakerJoinEntity.kt, SessionWithSpeakers.kt, SpeakerEntity.kt, SponsorEntity.kt, FireStore.kt, AnnouncementRepository.kt, ResponseToModelMapper.kt, SessionRepository.kt, SponsorRepository.kt, Announcement.kt, AudienceCategory.kt, Category.kt, ErrorMessage.kt, Filters.kt, FloorMap.kt, Lang.kt, LangSupport.kt, LoadingState.kt, LocaledString.kt, Room.kt, SearchResult.kt, Session.kt, SessionContents.kt, SessionFeedback.kt, SessionPage.kt, SessionType.kt, Speaker.kt, Sponsor.kt, SponsorCategory.kt, SystemProperty.kt, Lang.kt
 * Compiler version info: Konan: 1.0.3 / Kotlin: 1.3.11
 * Output kind: FRAMEWORK

exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /Users/a14042/.konan/dependencies/clang-llvm-6.0.1-darwin-macos/bin/llvm-lto command returned non-zero exit code: 1.
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:100)
        at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:66)
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:44)
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:40)
        at org.jetbrains.kotlin.backend.konan.LinkStage.llvmLto(LinkStage.kt:60)
        at org.jetbrains.kotlin.backend.konan.LinkStage.access$llvmLto(LinkStage.kt:18)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:221)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:18)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
        at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:213)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$7.invoke(KonanDriver.kt:107)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$7.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:137)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:111)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase(KonanPhases.kt:136)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:106)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:79)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:71)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:39)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:202)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:194)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:214)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:205)
        at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:37)
        at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:31)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:259)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :frontend:ios-combined:linkDebugFrameworkIOS FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:ios-combined:linkDebugFrameworkIOS'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
3 actionable tasks: 1 executed, 2 up-to-date
```

gradle version:
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by takahirom** [comment]
JVM .. Version..? 🤔 

```
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by takahirom** [comment]
Do you try `clean`?
https://github.com/JetBrains/kotlin-native/issues/1207

Can you compare your konanc args? 👀 
./gradlew clean --debug :frontend:ios-combined:packForXCode -PXCODE_CONFIGURATION=Debug |grep "konan"
https://gist.github.com/takahirom/8483ad104759362f0bee681e930adf8f

**Comment by takasfz** [comment]
Yes, I tried both clean and re-clone repo but it didn't solve it.

Here is my konanc args. It seems that `api.klib` and `model.klib` are additionally included..🤔
https://gist.github.com/takasfz/606a3e1441cb457083d0c0709ec4416c

**Comment by jmatsu** [comment]
I could reproduce this problem. 
This happened by running `./gradlew :frontend:ios-combined:packForXCode -PXCODE_CONFIGURATION=Debug` after cloning the repo again.
BUT I could compile the project successfuly on the previous directory... 🤷‍♂️ 
compileKotlinIOS will run on `data/api` and `model` in the new cloned directory. 🤔

**Comment by jmatsu** [comment]
maybe gradle cache is evil? I'm not sure but will investigate

**Comment by jmatsu** [comment]
@takasfz Could you please use the latest master and check again? 🙇

**Comment by takasfz** [comment]
@jmatsu Thank you so much. It solved! :tada:
