### ISSUE TITLE
Unresolved reference by java.lang.Throwable: Module 'ioscombined_commonMain' and module 'api-impl_commonMain' have the same content root

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#738]
## Kind (Required)

- Other

 ## Overview (Required)

- Probably Android Studio import error occured by this 

```
java.lang.Throwable: Module 'ioscombined_commonMain' and module 'api-impl_commonMain' have the same content root: file:///Users/takahirom/git/conference-app-2019/data/api-impl/src/commonMain/kotlin
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.loadModules(ModuleManagerImpl.java:357)
	at com.intellij.openapi.module.impl.ModuleManagerComponent$1.projectComponentsInitialized(ModuleManagerComponent.java:68)
	at sun.reflect.GeneratedMethodAccessor1739.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy56.projectComponentsInitialized(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:283)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:289)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$loadProjectWithProgress$13(ProjectManagerImpl.java:557)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by takahirom** [comment]
Currently workaround for this 


in settings.gradle

```
include ':frontend:android', //':frontend:ioscombined', ← comment out frontend:ioscombined
```

**Comment by takahirom** [comment]
Probably same source code is included from ioscombined
https://github.com/DroidKaigi/conference-app-2019/blob/master/frontend/ioscombined/build.gradle
