### ISSUE TITLE
タイムテーブル画面でスクロールを続けるとクラッシュ

### ISSUE THREAD

**Issue by sobaya-0141** [DroidKaigi/conference-app-2019#785]
## Overview (Required)

- タイムテーブル画面で右下にスクロールを続けるとクラッシュする。

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.confsched2019.debug, PID: 3462
    java.lang.IndexOutOfBoundsException: Wanted item at position -1 but an Item is a Group of size 1
        at com.xwray.groupie.Item.getItem(Item.java:114)
        at com.xwray.groupie.GroupAdapter.getItem(GroupAdapter.java:197)
        at com.xwray.groupie.GroupAdapter.getItem(GroupAdapter.java:207)
        at io.github.droidkaigi.confsched2019.session.ui.widget.TimetableCurrentTimeLineDecoration.calcLineHeight(TimetableCurrentTimeLineDecoration.kt:62)
        at io.github.droidkaigi.confsched2019.session.ui.widget.TimetableCurrentTimeLabelDecoration.onDrawOver(TimetableCurrentTimeLabelDecoration.kt:75)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4223)
        at android.view.View.updateDisplayListIfDirty(View.java:16167)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16130)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by sobaya-0141** [comment]
ストアから落とした物だとクラッシュせずにスケジュール部分が真っ白になりました。
<img src="https://user-images.githubusercontent.com/45986582/52193020-5f40e180-2890-11e9-8e9b-a61fd6450523.png" width=300>
